### ISSUE TITLE
Not notifying at all

### ISSUE THREAD

**Issue by lukaspour** [telia-oss/aws-notify-slack#2]
We use this lambda in neo-aws and it is just not working: After submit of a new alarm into SNS topic, Lambda says everything is ok, there are not errors in the log stream but no message is received in Slack. Could somebody check if the function works correctly and add some more debug logs into the runtime? Debugging would get much easier.

**Comment by mhd999** [comment]
Seems to work for me however you can use the test [event](https://github.com/telia-oss/aws-notify-slack/blob/master/snsEvent.json ) locally or when you deploy the lambda. 

Also added some logging to debug the function https://github.com/telia-oss/aws-notify-slack/pull/3
